name: Coleta diária de notícias

on:
  schedule:
    - cron: "0 16 * * *"   # 16:00 UTC = 13:00 America/Sao_Paulo
  workflow_dispatch:        # permite rodar manualmente pela aba Actions

jobs:
  test_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Opcional: baixe corpora do NLTK se seus testes exigirem tokenizers etc.
      - name: Baixar corpora NLTK (opcional)
        run: |
          python - << 'PY'
          import nltk
          try:
              nltk.download('punkt', quiet=True)
              nltk.download('stopwords', quiet=True)
              nltk.download('wordnet', quiet=True)
          except Exception as e:
              print("Aviso NLTK:", e)
          PY

      # --------- TESTES ---------
      - name: Teste rápido de instalação/verificação
        run: |
          python verificar_instalacao.py || true

      - name: Testes funcionais rápidos
        run: |
          python test_quick.py || true

      # --------- EXECUÇÃO PRODUTIVA ---------
      - name: Rodar coleta e enviar e-mail
        env:
          # Credenciais/Config vindas de Secrets (crie em Settings > Secrets and variables > Actions)
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO:  ${{ secrets.EMAIL_TO }}
          EMAIL_FROM_NAME: ${{ secrets.EMAIL_FROM_NAME }}
          EMAIL_SUBJECT_PREFIX: ${{ secrets.EMAIL_SUBJECT_PREFIX }}
          # Controle de saída (opcional)
          SAVE_TO_FILE: ${{ vars.SAVE_TO_FILE }}
          FILE_FORMAT:  ${{ vars.FILE_FORMAT }}
        run: |
          python coleta_agendada.py

      - name: Publicar artefatos de saída (CSV/HTML/JSON) - opcional
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios
          path: |
            output/*.html
            output/*.csv
            output/*.json
          if-no-files-found: ignore
